[tox]
# --------------------------------------------------------------------
#                         TOX FILE
# For testing packages in multiple env with different versions of 
# Python and OS. This file include configuratios both for local and
# remote CI.
# Python 3.8, 3.9, 3.10, 3.11, 3.12, and/or 3.13 are required
# when checking local coverage. To run just one interpreter:
#
#   $ tox -e py38
#
# It will run only the py38 defined interpreter, with python 3.8.
# --------------------------------------------------------------------

min_version = 4.26.0
requires = tox>=4
envlist = linter, type, black, py3{8,9,10,11,12,13}

# --------------------------------------------------------------------
#            Plugin for using tox with github actions
# --------------------------------------------------------------------
[gh-actions]
python =
    3.8: py38
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313, linter, type, black

# --------------------------------------------------------------------
#                       Base Test Enviroment
# --------------------------------------------------------------------

[testenv]
description = run unit tests
deps = 
    -r{toxinidir}/requirements_dev.txt
commands = pytest {posargs:tests/} 
# there is another command for more verbose outputs.
# TODO: check if tox supports different commands, so as to customize the different tests.

[testenv:py38]
description = interpreter for running python 3.8
basepython = {toxinidir}/bin/py38

[testenv:py39]
description = interpreter for running python 3.9
basepython = {toxinidir}/bin/py39

[testenv:py310]
description = interpreter for running python 3.10
basepython = {toxinidir}/bin/py310

[testenv:py311]
description = interpreter for running python 3.11
basepython = {toxinidir}/bin/py311

[testenv:py312]
description = interpreter for running python 3.12
basepython = {toxinidir}/bin/py312

[testenv:linter]
description = run linters
commands = flake8 . ':!Untitled1.ipynb'

[testenv:type]
description = run type checks using mypy
deps = mypy
commands = mypy {posargs:src }

[testenv:black]
description = run black for code formating
deps = black
commands = black src/amaru/ -v

# TODO: sphinx doc